@baseUrl = http://localhost:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxMDM5Nzg4MzY5NiwiaWF0IjoxNzU3OTcwMDk2LCJqdGkiOiI4Y2MxMGY2MDAwOWY0NGNhYjUzYjJlZTIxMTI5ZGZjYyIsInVzZXJfaWQiOiIxIn0.9C7cbGAv8QYyANBT0gHU7brwxtVrveGzyXa-0D5z0Io

### Notes
GET {{baseUrl}}/api/notes/
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/api/collections/1/notes/
Authorization: Bearer {{token}}

###

POST {{baseUrl}}/api/notes/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Example note",
  "content": "Example note"
}

### Collections
POST {{baseUrl}}/api/collections/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Example collection"
}

### Register
POST {{baseUrl}}/api/auth/register/
Content-Type: application/json

{
  "username": "Calcur4",
  "email": "caleb@calebcurry.com",
  "password": "password123"
}

### Login
POST {{baseUrl}}/api/auth/login/
Content-Type: application/json

{
  "username": "Calcur4",
  "password": "password123"
}

###

GET {{baseUrl}}/api/notes?collection_id=5
Authorization: Bearer {{token}}
