@baseUrl = http://localhost:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxMDQwMjczOTU2MywiaWF0IjoxNzYyODI1OTYzLCJqdGkiOiJjYTFjMDMwMTU0MDM0OGIxODdjZmY2NjA1YjRmZGM4NSIsInVzZXJfaWQiOiIxIn0.vUTKetNjN4UZkOj9LnTTF_WaB4gIlNs-LwLc3_9SGsM

### AI 
POST {{baseUrl}}/api/ai/
Authorization: Bearer {{token}}

### Notes
GET {{baseUrl}}/api/notes/
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/api/collections/1/notes/
Authorization: Bearer {{token}}

###

POST {{baseUrl}}/api/notes/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Example note 5345345",
  "content": "Example note",
  "collection": 13
}

### Collections
POST {{baseUrl}}/api/collections/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Example collection"
}

### Register
POST {{baseUrl}}/api/auth/register/
Content-Type: application/json

{
  "username": "Calcur4",
  "email": "caleb@calebcurry.com",
  "password": "password123"
}

### Login
POST {{baseUrl}}/api/auth/login/
Content-Type: application/json

{
  "username": "calebcurry",
  "password": "Password123"
}

###

GET {{baseUrl}}/api/notes?collection_id=5
Authorization: Bearer {{token}}
