GET http://localhost:8000/api/notes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3NDQ5MDE0LCJpYXQiOjE3NTc0NDYwMTQsImp0aSI6ImJjZTIzYzA1YjM1NzQ0MDdhN2RhNzk0Y2NhNTBlYTkyIiwidXNlcl9pZCI6IjYifQ.RZcjisUKA7V_FNKR-SUWrTcCYIQlTpe28tKsMtysDKg

###

POST http://localhost:8000/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3NDQ5NTk0LCJpYXQiOjE3NTc0NDY1OTQsImp0aSI6IjFhMDM0NThlMzFiMTQ5YzViNjMxZGI0ZmZkMzM5MDE1IiwidXNlcl9pZCI6IjYifQ.gMideS8O-mRGqUSmBsjYzzwjoqHwtcSJBhh5U68b4vY

{
    "title": "Example next user",
    "content": "Example content next user",
    "collection": 3
}

###

POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
    "username": "Calcur4",
    "email": "caleb@calebcurry.com",
    "password": "password123"
}

###

POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
    "username": "Calcur3",
    "password": "password123"
}

###

POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
    "username": "Calcur4",
    "password": "password123"
}


### 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3Mzc0NTUyLCJpYXQiOjE3NTczNzE1NTIsImp0aSI6ImFjNjFhNjUzNjA3NjQ1NzNiNTIzNzllZDMyMTdiZjQ2IiwidXNlcl9pZCI6IjUifQ.-oD541OBKAIMT6g52y2DYIBlZ8vgmUP6nyzRLZqe9AQ


eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3Mzc0NTM2LCJpYXQiOjE3NTczNzE1MzYsImp0aSI6ImMzOTkwZDllMjBjMDRlM2U4MjZkYjZjM2MwMTljMGFmIiwidXNlcl9pZCI6IjYifQ.itsM9E_RwcYH3EF8VDmryX0N8XIc4VjBA_WOv2saKPU