GET http://localhost:8000/api/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3MzU3MjgwLCJpYXQiOjE3NTczNTY5ODAsImp0aSI6IjI0NGZiODQ0ODc4MzQxYzE5YjBiZWE0YWYwOWEyZDdmIiwidXNlcl9pZCI6IjEifQ.TDREIvRpRUVvCRalnOXwsKMr7-iB_b8TtBmbnuZNGrw